"use client"
// import type { Metadata } from "next";
import { Roboto, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Footer from "./_componants/footer";
import Navbar from "./_componants/navbar";
import { createContext, Suspense, useEffect, useState } from "react";
import { auth, db } from "./_config/firebase";
import { onAuthStateChanged } from "firebase/auth";
import { doc, getDoc } from "firebase/firestore";
import DATRA from "./_context/Context";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"]
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }: any) {

  let [data, setData] = useState(false)

  useEffect(() => {
    const isloged = () => onAuthStateChanged(auth, (user) => {
      if (user) {
        setData(true)
        if (!localStorage.getItem("likes")) {
          localStorage.setItem("likes", JSON.stringify([]))
        }
      } else {
        setData(false)
      }
    }, (error) => {
      console.log("error", error)
    })
    return () => {
      isloged()
    }
  }, [])



  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <DATRA>
            <>
              {data ? <Navbar /> : null}
              {children}
              {data ? <Footer /> : null}
            </>
          </DATRA>
        </body>
      </html>
    </>
  );
}
